apiVersion: v1
kind: Namespace
metadata:
  name: monitoring-demo
  labels:
    purpose: infra
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: infra-node-exporter
  namespace: monitoring-demo
  labels:
    app: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
      - name: node-exporter
        image: quay.io/prometheus/node-exporter:latest
        ports:
        - containerPort: 9100
        securityContext:
          privileged: true
      hostNetwork: true
      hostPID: true
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
